include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  rules:
    - always_declare_return_types
    - prefer_final_in_for_each
    - prefer_single_quotes
    - await_only_futures: true

analyzer:
  strong-mode:
    # implicit-casts: false
    # implicit-dynamic: false
  exclude:
    - lib/**.freezed.dart
    - lib/**.g.dart
    - lib/generated
  errors:
    # invalid_annotation_target: ignore
    todo: ignore
