name: Deploy

on:
  release:
    types: [created]

jobs:
  build:
    if: ${{ github.repository == 'flutter-seoul/fluter_seoul' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: true
          skipTests: true
